"""
Build the PixVerse prompt pack (PROMPTS.md) from style.json + manifest.json.

    python3 pipeline/pixverse/prompts.py

Paste each prompt into PixVerse (text-to-video), download the result and save
it as pipeline/pixverse/raw/<asset id>.mp4, then run process.py.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))


def full_prompt(style, asset):
    parts = [style["prefix"], asset["prompt"]]
    if asset.get("chroma"):
        parts.append(style["chroma_suffix"])
    return ", ".join(parts)


def main():
    style = json.load(open(os.path.join(HERE, "style.json")))
    manifest = json.load(open(os.path.join(HERE, "manifest.json")))
    d = style["defaults"]
    out = [
        "# PixVerse prompt pack — VESTIGE//NULL",
        "",
        "Generated by `pipeline/pixverse/prompts.py` from `style.json` and `manifest.json`; edit those, not this file.",
        "",
        "For each asset: open PixVerse → **Text to Video**, paste the prompt and negative prompt, use the settings listed,",
        f"then save the download as `pipeline/pixverse/raw/<id>.mp4`. Defaults: model **{d['model']}**, quality **{d['quality']}**,",
        f"duration **{d['duration']}s**, motion **{d['motion_mode']}**. Then run `python3 pipeline/pixverse/process.py`.",
        "",
        "Assets marked *green screen* are keyed to transparency, so keep the background a flat, pure green.",
        "If a generation drifts off-style, reroll with the same prompt and a different seed rather than editing the style prefix.",
        "",
        "Where each asset shows up in the game:",
        "",
        "| kind | used for |",
        "| --- | --- |",
        "| character | dialogue portraits (animated poster frame) |",
        "| enemy | encounter splash + battle apparition card (Blender-built GLB) |",
        "| environment | looping video backdrop wrapped around the horizon (field / battle) |",
        "| fx | spell burst sprite sheet (Rift Burst and death effects) |",
        "",
    ]
    for a in manifest["assets"]:
        out += [
            f"## `{a['id']}` — {a['kind']}{' · green screen' if a.get('chroma') else ''}",
            "",
            f"Aspect **{a.get('aspect_ratio', d['aspect_ratio'])}** · duration **{a.get('duration', d['duration'])}s** · save as `raw/{a['id']}.mp4`",
            "",
            "**Prompt**",
            "",
            "```text",
            full_prompt(style, a),
            "```",
            "",
            "**Negative prompt**",
            "",
            "```text",
            style["negative"] + (", busy background, gradient background" if a.get("chroma") else ""),
            "```",
            "",
        ]
    path = os.path.join(HERE, "PROMPTS.md")
    open(path, "w").write("\n".join(out))
    print("wrote", os.path.relpath(path, os.getcwd()), f"({len(manifest['assets'])} assets)")


if __name__ == "__main__":
    main()
